### ISSUE TITLE
Territory field not ISO 3166-1 alpha3 code

### ISSUE THREAD

**Issue by chr1sdi** [openregister/registry-data#43]
https://github.com/openregister/registry-data/blob/master/data/beta/field/territory.yaml#L6

says that the codes are ISO 3166-1 alpha3 which does not seem to be true:
https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3

**Comment by karlbaker02** [comment]
Also by having a mixture of ISO and non-ISO codes in this register, we have no way to differentiate between them. This feels to me like the description cannot be valid whilst this is the situation.
